# Generated by Django 3.2.8 on 2022-01-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.TextField(max_length=10, unique=True)),
                ('name', models.TextField(blank=True, max_length=64, null=True)),
                ('department', models.TextField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=40, null=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available '), ('NOT_AVAILABLE', 'not available')], default='AVAILABLE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('class_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cls_room', serialize=False, to='school.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.teacher')),
            ],
        ),
    ]
