# Generated by Django 3.2.8 on 2022-01-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_room',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cls_room', serialize=False, to='school.student'),
        ),
    ]
