# Generated by Django 3.2.8 on 2022-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20220121_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
