# Generated by Django 3.2.8 on 2022-01-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_classroom_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='start_date',
        ),
    ]
