# Generated by Django 3.2.8 on 2022-01-21 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20220121_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
